---
abstract: 'extra sugar for method delegation'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::NiftyDelegation
name: MooseX-NiftyDelegation
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 2.00
  Sub::Exporter: 0
  perl: 5.8.0
  thanks: 0.001
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-NiftyDelegation
  homepage: https://metacpan.org/release/MooseX-NiftyDelegation
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-niftydelegation
version: 0.002
